name: GroovyMedia
favicon: null
layout_spectrum: 0.8735490962862968
typography_spectrum: 0.22051957808434963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#beb6ab'
    - '#070908'
    - '#5d250c'
    - '#7d7d75'
  brandStrength: 0.5270687502343208
  lightness: 0.9161683637648821
  saturation: 0.2886976576410234
  rhythmicContrast: 0.6027496056631207
purpose: []
